name: gitleaks
on: 
  push:
    branches:
      main
jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}} # Only required for Organizations, not personal accounts.
          GITKEAKS_ENABLE_ARTIFACT_UPLOAD: false

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: result
          path: ${{github.workspace}}/results.sarif

      
